spring:
  application:
    name: SMore

  profiles:
    active: local  # default to 'local', switch to 'dev' as needed

  datasource:
    url: jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://awseb-e-rzsgcs5fes-stack-awsebrdsdatabase-mxq674epv4uu.c1uww8qk4aii.ap-northeast-2.rds.amazonaws.com/ebdb
    username: smore
    password: smore123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
